### ISSUE TITLE
Systems: Cannot update batchSchedulerProfile

### ISSUE THREAD

**Issue by Tyler-Clemens** [tapis-project/tapis-java#39]
Trying to update _batchSchedulerProfile_ from "None" to "tacc" in the system definition did not work using either a PATCH or a PUT request. Creating a new system with _batchSchedulerProfile_ set as "tacc" also returned "None" when creating a brand new system and fetching it.

System definition used to create new system:
<img width="364" alt="Screen Shot 2021-11-02 at 10 20 54 AM" src="https://user-images.githubusercontent.com/51714485/139883900-dfcc2787-4e85-4de5-9420-dded1f11f607.png">

Fetching system after creation:
<img width="250" alt="Screen Shot 2021-11-02 at 10 22 57 AM" src="https://user-images.githubusercontent.com/51714485/139884478-c8634025-d455-4528-ac5f-42f0f1b6278d.png">

**Comment by scblack321** [comment]
moving issue to tapis-systems repo.
